# .github/workflows/scheduled-builds.yml
name: CronJob

on:
  schedule:
    - cron: '0 * * * *'
jobs:
  build:
    name: Trigger Site Visit
    runs-on: ubuntu-latest
    steps:
      - name: cURL request
        run: curl https://eds-store-mern.herokuapp.com/
